services:
  - type: web
    name: django-cms
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn content_cms.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: content_cms.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
