# Generated by Django 5.2 on 2025-04-18 10:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
